# Introduction


In [1]:
#| output: false
using Memoize, BenchmarkTools

## Basics

Julia was built for doing applied math and comes with a simple syntax. You can assign variables by plain `=` like in *Python* or *R*.

In [2]:
a = 3

3

Let's do some calculations:

In [3]:
2a + a^2

15

Quite common in Julia is the use of greek symbols and some other cool utf-8 stuff. Typing backslash \ and then the latex name of something, and finish with pressing TAB, you can insert many symbols quite conveniently. Try it out!

In [4]:
θ = 1.34; 2θ

2.68

Some variables are already defined:

In [5]:
π

π = 3.1415926535897...

We can also have super and subscripts.

In [6]:
a² = a*a # a\^2 + tab

9

## If/Else 

In Julia you have a multiline if/else block and the ternary question mark operator ``?``.

In [7]:
if a == 1
  println("It's one Jonny!! It's one!!")
elseif a in (2:5)
  println("It is a $a.")
else
  println("No idea!")
end

It is a 3.


In [8]:
a == 3 ? "three" : "other"

"three"

If the comparison is `true` then the first statement happens, else the second statement happens.

In [9]:
a² > 10 ? "Yes!" : "Oh no!"

"Oh no!"

In [10]:
if a == 3
  μ = 2a
else
  μ = 0
end

6

We can use `@show` to be explict on the output:

In [11]:
@show μ;

μ = 6


In [12]:
a == 3 ? ϕ = 3a : ϕ = 0
@show ϕ;

ϕ = 9


In addition, we have short-cycling AND `&&`, and OR `||`. In both cases, the first argument has to be a boolean, however the last argument can be anything.

`&&` evaluates and returns the second argument if the first is true.

In [13]:
a == 3 && "The power of three!"

"The power of three!"

Otherwise, `&&` returns false.

In [14]:
3a > 10 && "I'm bigger than 10"

false

In [15]:
ϕ == 9 && @show 2a;

2a = 6


`||` evaluates and returns the second argument if the first is false.

In [16]:
3a > 10 || println("Three times $a is less than 10")

Three times 3 is less than 10


We see these in loops or functions commonly, where it is combined with `return`, `continue` or `break`.

## Functions

While variables are the synapsis, the brain of Julia are its functions. Really: If you understood functions in Julia, you are ready to work in Julia.

There are many functions available builtin, we already saw a couple of them.

An example of a function:

In [17]:
isodd(3), iseven(a), a + a, +(a, a), 1 in (1,2), in(1, [1,2,3])

(true, false, 6, 6, true, true)

Generating a vector `[start:increment:end;]`

In [18]:
[1:1:4;]

4-element Vector{Int64}:
 1
 2
 3
 4

We can **broadcast** functions over a vector with a dot:

In [19]:
a .+ [1:1:4;]

4-element Vector{Int64}:
 4
 5
 6
 7

It is relatively simple to define our own functions:

In [20]:
"""
    add2(x)
    
adds 2 to the given input and returns the result
"""
add2(x) = x + 2

add2

There is a second syntax to create functions which span multiple lines:

In [21]:
function add2(x, y)
	x₁ = add2(x) 
	y₁ = add2(y)
	return x₁, y₁
end

add2 (generic function with 2 methods)

Here, we apply the function over only one argument. Note how the output is reported.

In [22]:
add2(7), add2(9), add2(100)

(9, 11, 102)

Here, we apply the function over two arguments:

In [23]:
add2(1, 2)

(3, 4)

There is support for an arbitrary number of positional and keyword arguments. Functions can be overloaded with an arbitrary number of arguments, as well as arbitrary argument types.

In [24]:
func(a::Int) = a+2

func (generic function with 1 method)

The name of our new function is `func`, in the previous command, when `a` is an integer, adds 2 to the number. Let's add other possibilities:

In [25]:
begin
	func(a::AbstractFloat) = a/2
	func(a::Rational) = a/11
	func(a::Complex) = sqrt(a) 
	func(a, b::String) = "$a, $b"
end

func (generic function with 5 methods)

Let's test our function when `a` is an integer:

In [26]:
func(20)

22

But what about if `a` is a float?

In [27]:
func(20.0)

10.0

A rational?

In [28]:
func(3/4)

0.375

Testing the last method:

In [29]:
func(5, "Hola!")

"5, Hola!"

## Memoize and BenchmarkTools

By now, we have everything we need to define our own fibonacci function :) https://en.wikipedia.org/wiki/Fibonacci_number

In [30]:
"""
  fibonacci(n)

Returns the nth fibonacci number
"""
function fibonacci(n)
  if n <= 2
    return 1
  else
    return fibonacci(n - 1) + fibonacci(n - 2)    
  end
end

fibonacci

In [31]:
fibonacci(2), fibonacci(3), fibonacci(7), fibonacci(10)

(1, 2, 13, 55)

This generates optimal code for small numbers of `n`, however gets quickly out of reach for larger `n`. We can optimize the function by reusing already computed results. A quick trick to do so is to use the ``@memoize`` Macro from the ``Memoize`` package.

In [32]:
@memoize function fibonacci_mem(n)
  if n <= 2
      return 1
    else
      return fibonacci_mem(n - 1) + fibonacci_mem(n - 2)    
    end
end

fibonacci_mem (generic function with 1 method)

With the help of the famous `@benchmark` macro from the `BenchmarkTools` package you can directly compare the time and memory footprint of the two functions.

In [33]:
@benchmark fibonacci(30)

BenchmarkTools.Trial: 2220 samples with 1 evaluation.
 Range (min … max):  2.156 ms …  2.497 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     2.241 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.252 ms ± 32.755 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

                     █ ▁                                      
  ▂▂▂▂▁▁▂▁▁▁▂▁▂▂▁▁▁▂▄█▇█▆▇▅▅▅▄▄▅▄▄▄▃▄▄▃▄▃▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂ ▃
  2.16 ms        Histogram: frequency by time        2.35 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.

Now, the benchmark of the memoize version:

In [34]:
@benchmark fibonacci_mem(30)

BenchmarkTools.Trial: 10000 samples with 993 evaluations.
 Range (min … max):  36.169 ns … 66.382 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     36.254 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   36.419 ns ±  0.904 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █▇▅▂              ▁                                         ▂
  ████▅▄▁▄▄▁▄▅▄▄▃▃▅▅██▇▅▄▄▄▄▃▄▃▃▃▄▄▃▅▅▄▄▄▄▅▄▃▅▄▃▄▅▃▅▄▄▄▄▅▃▅▅▆ █
  36.2 ns      Histogram: log(frequency) by time      41.3 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

Wow, that was fast!! As you can see the memoization kicks in and we have about constant access time.

## Arrays

Arrays are the best supported DataType in Julia, it is multidimensional and highly optimized. You use it as both `list` and `numpy.array` in Python, i.e. no more switching between worlds.

Create a column vector with respective elements:

In [35]:
[1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

We can generate the same result using a sequence:

In [36]:
[1:1:4;]

4-element Vector{Int64}:
 1
 2
 3
 4

To create a row vector, we remove the commas:

In [37]:
[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

We can create a matrix relatively easy (a small matrix, of course!):

In [38]:
[
  1 2
  3 4
]

2×2 Matrix{Int64}:
 1  2
 3  4

There are many common functions for dealing with Arrays, most importantly for construction. Using `Array`:

In [39]:
Array{String}(undef, (2, 5))

2×5 Matrix{String}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

Using `Matrix`:

In [40]:
Matrix{String}(undef, (4, 4))

4×4 Matrix{String}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

Using fill, first example, all zero values

In [41]:
fill(0, (3, 4))

3×4 Matrix{Int64}:
 0  0  0  0
 0  0  0  0
 0  0  0  0

A matrix with all elements equal to 5:

In [42]:
fill(5, (6, 3))

6×3 Matrix{Int64}:
 5  5  5
 5  5  5
 5  5  5
 5  5  5
 5  5  5
 5  5  5

We have index support:

In [43]:
β = [100:100:300;]

3-element Vector{Int64}:
 100
 200
 300

The second element:

In [44]:
β[2]

200

The last element!

In [45]:
β[end]

300

A beautiful aspect of julia is that many many things are not at all hardcoded, but actually have generic implementations under the hood.

One of these is applying a function elementwise to an array, also called **Broadcasting**.

In [46]:
add2.(β)

3-element Vector{Int64}:
 102
 202
 302

The dot syntax translates to:

In [47]:
broadcast(add2, β)

3-element Vector{Int64}:
 102
 202
 302

Evaluate if each element of β is equal to 100:

In [48]:
β .== 100

3-element BitVector:
 1
 0
 0

If we do not broadcast, the comparison is NOT elementwise:

In [49]:
β == 100

false

We can *transpose* an Array by using `'`:

In [50]:
β .+ β'

3×3 Matrix{Int64}:
 200  300  400
 300  400  500
 400  500  600

Unlike `Numpy` in Python, Julia's Arrays can hold any type of data.

In [51]:
mycombine(a, b) = (a, b, [a + b])

mycombine (generic function with 1 method)

In [52]:
mycombine.(β, β')

3×3 Matrix{Tuple{Int64, Int64, Vector{Int64}}}:
 (100, 100, [200])  (100, 200, [300])  (100, 300, [400])
 (200, 100, [300])  (200, 200, [400])  (200, 300, [500])
 (300, 100, [400])  (300, 200, [500])  (300, 300, [600])

Alternatively, we can construct the same with a *multi-dimensional* for comprehension.

In [53]:
[mycombine(x, y) for x in β, y in β]

3×3 Matrix{Tuple{Int64, Int64, Vector{Int64}}}:
 (100, 100, [200])  (100, 200, [300])  (100, 300, [400])
 (200, 100, [300])  (200, 200, [400])  (200, 300, [500])
 (300, 100, [400])  (300, 200, [500])  (300, 300, [600])

We can see that perfomance improved drastically, while now having a memory footprint on each call.

## Named tuples and Structs

### Named tuples

In practice we often have a bunch of variables we need to handle at once.

- In julia we can construct our own types for this, but they may be a bit clumsy at times.
- Luckily there is also a simple way to use the alternative: *named tuples*, which we can use for fast development.

We already saw *tuples* and tuple destructing.

In [54]:
x, y = (1, 2)

(1, 2)

In [55]:
x + y

3

We can also give name to tuples:

In [56]:
namedtuple = (key=1, value=2)

(key = 1, value = 2)

In [57]:
namedtuple.key

1

### Struct

This is one of the most useful tools for fast prototyping. There is even no performance penalty in using `namedtuples`, actually it is able to create optimal code.

In case we want to define our own types for a more stable interface between different parts of our code you can use `struct`.

In [58]:
struct MyType
  key::Int        # always specify the types by prepending ::
  value::String
end

In [59]:
MyType(3, "hi").value 

"hi"

If we want flexible types, the best way is to parameterise the types.

In [60]:
struct MyType2{Key, Value}
  key::Key
  value::Value
end

In [61]:
MyType2("yeah", true)

MyType2{String, Bool}("yeah", true)

:::{.callout-note}
From the last output, we can see that types were automatically inferred.
:::

In [62]:
MyType2("yeah", true).key

"yeah"

There is also the alternative of not specifying types at all:

In [63]:
struct MyType3
  key
  value
end

Which is equivalent to specifying:

In [64]:
struct MyType3
  key::Any
  value::Any
end

:::{.callout-important}
Very important to know is that this leads to pour type inference and hence pourer performance. If we run: `MyType3(1,"value").key`, Julia does not know any longer that the key is actually of type Int, this was forgotten when wrapped into the MyType3. Hence not much code optimization can be done.
:::

In [65]:
MyType3(1,"value").key

1

Always prefer to parameterise types, as it is not much work and gives optimal performance.

In [66]:
func(a::MyType2) = "$(a.key): $(a.value)"

func (generic function with 6 methods)

## Loops

In [67]:
for i in 1:4
  println(i)
end

1
2
3
4


:::{.callout-caution}
However what does not work is adapting GLOBAL variables within a loop. It does not work within scripts and not in the Julia shell. Surprisingly, and conveniently, it works in the Jupyter Notebook though.
:::

In [68]:
let
	a = 0
	for i in 1:4
		a += i
	end
	a
end

10